name: Build and Publish

on:
  push:

env:
  IMAGE_NAME: polybot

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install wheel
          pip install -r ./dev-requirements.txt
          black --check ./polybot
          flake8 ./polybot
          mypy ./polybot --ignore-missing-imports

  build:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build . --tag $IMAGE_NAME

      - name: Push image to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

          IMAGE_ID=ghcr.io/${{ github.repository }}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=${{ github.sha }}

          docker tag $IMAGE_NAME $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:${{ github.sha }}
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
